In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
# Challenge 1: Financial Analyst’s Dilemma
import numpy as np

np.random.seed(42)  # For reproducibility
stock_prices = np.random.randint(100, 500, (30, 5))

avg_prices = np.mean(stock_prices, axis=0)

max_price = np.max(stock_prices)
max_day, max_company = np.unravel_index(np.argmax(stock_prices), stock_prices.shape)

normalized_prices = (stock_prices - stock_prices.min()) / (stock_prices.max() - stock_prices.min())

risky_days = np.where(stock_prices < 200)

print("Average stock prices:", avg_prices)
print(f"Highest price recorded: {max_price} at Day {max_day}, Company {max_company}")
print("Normalized Prices:\n", normalized_prices)
print("Risky Investment Days:")
for day in np.unique(risky_days[0]):
    print(f"Day {day+1}: {stock_prices[day][stock_prices[day] < 200]}")

Average stock prices: [309.1        279.53333333 320.33333333 309.03333333 305.93333333]
Highest price recorded: 497 at Day 28, Company 2
Normalized Prices:
 [[0.25505051 0.87626263 0.67929293 0.26515152 0.17676768]
 [0.47222222 0.0479798  0.25505051 0.3030303  0.53787879]
 [0.83080808 0.21717172 0.93686869 0.24747475 0.9040404 ]
 [0.37878788 0.32575758 0.37373737 0.77525253 0.64646465]
 [0.86363636 0.73737374 0.96969697 0.47979798 0.69444444]
 [0.40151515 0.78787879 0.05050505 0.63383838 0.59090909]
 [0.86616162 0.11868687 0.14393939 0.42424242 0.46969697]
 [0.67929293 0.47474747 0.43686869 0.12373737 0.91414141]
 [0.13383838 0.61111111 0.8030303  0.32575758 0.77020202]
 [0.33585859 0.0479798  0.82575758 0.41666667 0.68686869]
 [0.97474747 0.21969697 0.79292929 0.03030303 0.60606061]
 [0.66414141 0.86868687 0.12878788 0.96969697 0.85353535]
 [0.22727273 0.92171717 0.66161616 0.08333333 0.51515152]
 [0.19949495 0.12121212 0.9040404  0.97474747 0.        ]
 [0.97979798 0.13131313 0.2626

In [8]:
import numpy as np

resources=np.random.randint(15,50,(6,3))
total_resources=np.sum(resources,axis=0)
max_resource=np.max(resources)
max_month,max_type=np.unravel_index(np.argmax(resources),resources.shape)
resource_names=["Oxygen","Water","Food"]

std_dev=np.std(resources,axis=0)
transposed_resources=resources.T

print(f"Total resources needed (tons): Oxygen: {total_resources[0]}, Water: {total_resources[1]}, Food: {total_resources[2]}")
print(f"Highest consumption in a month: {resource_names[max_type]} ({max_resource} tons in month {max_month+1})")
print(f"Standard deviation of consumption: Oxygen: {std_dev[0]:.1f}, Water: {std_dev[1]:.1f}, Food: {std_dev[2]:.1f}")
print("Transposed Matrix:")
print(transposed_resources)

Total resources needed (tons): Oxygen: 196, Water: 182, Food: 170
Highest consumption in a month: Water (47 tons in month 4)
Standard deviation of consumption: Oxygen: 12.3, Water: 11.1, Food: 12.9
Transposed Matrix:
[[38 17 16 46 33 46]
 [26 31 42 47 16 20]
 [16 16 37 15 40 46]]


In [9]:
# Challenge 3: Basketball Performance Analyzer
points = np.random.randint(10, 40, (5, 10))

avg_points = np.mean(points, axis=1)

total_points = np.sum(points, axis=1)
best_player = np.argmax(total_points)
worst_player = np.argmin(total_points)

exceptional_games = {i: np.where(points[i] > 30)[0] + 1 for i in range(5)}

total_sorted_indices = np.argsort(total_points)[::-1]

print("Average points per game:", avg_points)
print(f"Best-performing player: Player {best_player+1} (Total: {total_points[best_player]} points)")
print(f"Worst-performing player: Player {worst_player+1} (Total: {total_points[worst_player]} points)")
print("Games with scores above 30:")
for player, games in exceptional_games.items():
    if len(games) > 0:
        print(f"Player {player+1}: Games {list(games)}")
print("Sorted Players by Total Points:")
for rank, idx in enumerate(total_sorted_indices, 1):
    print(f"{rank}. Player {idx+1} - {total_points[idx]} points")

Average points per game: [25.4 22.1 26.9 21.  27.7]
Best-performing player: Player 5 (Total: 277 points)
Worst-performing player: Player 4 (Total: 210 points)
Games with scores above 30:
Player 1: Games [np.int64(1), np.int64(3), np.int64(5), np.int64(6), np.int64(9)]
Player 2: Games [np.int64(4), np.int64(10)]
Player 3: Games [np.int64(1), np.int64(4), np.int64(7), np.int64(8)]
Player 4: Games [np.int64(1)]
Player 5: Games [np.int64(5), np.int64(6), np.int64(7), np.int64(9), np.int64(10)]
Sorted Players by Total Points:
1. Player 5 - 277 points
2. Player 3 - 269 points
3. Player 1 - 254 points
4. Player 2 - 221 points
5. Player 4 - 210 points
